package project

import (
	"fmt"
	"text/template"
)

// TemplateContext holds variables for template rendering.
type TemplateContext struct {
	ProjectName    string
	PersonaName    string
	ConfigFormat   string // meml, yaml, json
	DocStyle       string // code-first, prose-first, balanced
	TestingStyle   string // unit-focused, integration-heavy
	Theme          string // dark, light, auto
	ProjectType    string // cli, library, service, tool
	Language       string // go, node, python, rust
}

// Templates stores template strings for different project types.
var Templates = map[string]map[string]string{
	"go": {
		"cli": goCliTemplate,
		"lib": goLibTemplate,
	},
}

const (
	goCliTemplate = `package main

import (
	"flag"
	"fmt"
	"os"
)

// {{.ProjectName}} — auto-generated by waldo
// Persona: {{.PersonaName}}
// Config format: {{.ConfigFormat}} | Testing: {{.TestingStyle}}

func main() {
	flag.Parse()

	if len(os.Args) < 2 {
		usage()
		os.Exit(1)
	}

	// TODO: Implement your CLI here
	fmt.Println("Hello from {{.ProjectName}}")
}

func usage() {
	fmt.Fprintf(os.Stderr, "Usage: {{.ProjectName}} [command] [args]\n")
}
`

	goLibTemplate = `package {{.ProjectName}}

// Package {{.ProjectName}} — auto-generated by waldo
// Persona: {{.PersonaName}}
// Testing style: {{.TestingStyle}}

// TODO: Add your library code here

// Example function
func Example(input string) string {
	return "TODO: implement " + input
}
`
)

// RenderTemplate renders a template with context.
func RenderTemplate(templateStr string, ctx *TemplateContext) (string, error) {
	tmpl, err := template.New("project").Parse(templateStr)
	if err != nil {
		return "", fmt.Errorf("template parse error: %w", err)
	}

	var output []byte
	buf := &buffer{data: output}

	if err := tmpl.Execute(buf, ctx); err != nil {
		return "", fmt.Errorf("template render error: %w", err)
	}

	return buf.String(), nil
}

// buffer is a simple bytes buffer for template execution.
type buffer struct {
	data []byte
}

func (b *buffer) Write(p []byte) (int, error) {
	b.data = append(b.data, p...)
	return len(p), nil
}

func (b *buffer) String() string {
	return string(b.data)
}

// MakefileTemplate generates a Makefile based on preferences.
func MakefileTemplate(ctx *TemplateContext) string {
	testing := ""
	if ctx.TestingStyle == "unit-focused" {
		testing = `test:
	go test ./... -v

test-coverage:
	go test ./... -v -cover
`
	} else {
		testing = `test:
	go test ./... -v -race

test-coverage:
	go test ./... -v -cover -race

test-integration:
	go test ./... -v -tags=integration
`
	}

	makefile := fmt.Sprintf(`# Makefile — auto-generated by waldo

PROJECT = %s
PERSONA = %s (%s | %s)

build:
	go build -o bin/$(PROJECT) ./cmd/$(PROJECT)/

%s
fmt:
	gofmt -w .

vet:
	go vet ./...

clean:
	rm -rf bin/

.PHONY: build test test-coverage test-integration fmt vet clean
`, ctx.ProjectName, ctx.PersonaName, ctx.DocStyle, ctx.TestingStyle, testing)

	return makefile
}

// READMETemplate generates a README based on project type and preferences.
func READMETemplate(ctx *TemplateContext) string {
	intro := ""
	if ctx.ProjectType == "cli" {
		intro = fmt.Sprintf("# %s\n\nCLI tool created with waldo.\n\n## Features\n\n- TODO: Add features\n\n## Install\n\n```bash\ngo install github.com/yourname/%s@latest\n```\n\n## Usage\n\n```bash\n%s --help\n```\n\n", ctx.ProjectName, ctx.ProjectName, ctx.ProjectName)
	} else if ctx.ProjectType == "lib" || ctx.ProjectType == "library" {
		intro = fmt.Sprintf("# %s\n\nGo library created with waldo.\n\n## Install\n\n```bash\ngo get github.com/yourname/%s\n```\n\n## Usage\n\n```go\nimport \"%s\"\n```\n\n", ctx.ProjectName, ctx.ProjectName, ctx.ProjectName)
	}

	return intro + "\n## Documentation\n\nTODO: Add documentation\n"
}

// MemlConfigTemplate generates an example config file in MEML format.
func MemlConfigTemplate(ctx *TemplateContext) string {
	config := fmt.Sprintf("# %s config — auto-generated by waldo\n\n[meta]\nproject = \"%s\"\nversion = \"0.1.0\"\npersona = \"%s\"\n\n[app]\nname = \"%s\"\ndebug = false\n\n[server]\nhost = \"localhost\"\nport = 8080\n\n[secrets]\napi_key = \"\"\n", ctx.ProjectName, ctx.ProjectName, ctx.PersonaName, ctx.ProjectName)
	return config
}

// YamlConfigTemplate generates an example config file in YAML format.
func YamlConfigTemplate(ctx *TemplateContext) string {
	config := fmt.Sprintf("# %s config — auto-generated by waldo\n\nmeta:\n  project: %s\n  version: \"0.1.0\"\n  persona: %s\n\napp:\n  name: %s\n  debug: false\n\nserver:\n  host: localhost\n  port: 8080\n\nsecrets:\n  api_key: \"\"\n", ctx.ProjectName, ctx.ProjectName, ctx.PersonaName, ctx.ProjectName)
	return config
}
