package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	flag.Parse()

	// Get current working directory (project root)
	projectRoot, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ Failed to get working directory: %v\n", err)
		os.Exit(1)
	}

	// Load waldo config
	home, err := os.UserHomeDir()
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ Failed to get home directory: %v\n", err)
		os.Exit(1)
	}

	personasDir := filepath.Join(home, ".config", "waldo", "personas")
	activeFile := filepath.Join(personasDir, ".active")

	// Read active persona
	activeData, err := os.ReadFile(activeFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ No active persona found. Run: waldo use agent/default\n")
		os.Exit(1)
	}

	activeName := strings.TrimSpace(string(activeData))
	personaPath := filepath.Join(personasDir, activeName+".meml")

	// Read persona file
	personaData, err := os.ReadFile(personaPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ Persona file not found: %s\n", personaPath)
		os.Exit(1)
	}

	// Convert MEML to Cursor workspace rules format
	cursorRules := memlToCursorRules(string(personaData), activeName)

	// Write .cursorrules file in project root
	cursorRulesPath := filepath.Join(projectRoot, ".cursorrules")
	if err := os.WriteFile(cursorRulesPath, []byte(cursorRules), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "❌ Failed to write .cursorrules: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ Synced persona '%s' to %s\n", activeName, cursorRulesPath)
}

// memlToCursorRules converts a MEML persona to Cursor workspace rules format.
// Cursor rules are Markdown-based and placed in .cursorrules file.
func memlToCursorRules(memlContent string, personaName string) string {
	// TODO: Parse MEML and extract tone, verbosity, voice values
	// For now, this is a stub that returns a valid .cursorrules template

	rules := fmt.Sprintf(`# Cursor Rules — Generated by waldo

**Persona:** %s

## Instructions

This file is auto-generated from your waldo persona. Update your persona with:

    waldo use agent/your-persona-name

Or manually edit this file to customize Cursor's behavior.

### Tone & Voice

Apply these personality traits to your code suggestions:
- Stay concise and direct
- Use clear, technical language
- Prioritize clarity over cleverness

### Format

- Use best practices from the codebase
- Match existing code style
- Add helpful comments for complex logic

---

**Generated by:** waldo v0.2
**Source:** ~/.config/waldo/personas/%s.meml
`, personaName, personaName)

	return rules
}
